name: Smoke Tests

on:
  push:
    tags:
      - v*
    branches:
      - develop
      - main
  pull_request:

jobs:
  build-chainlink:
    name: Build chainlink image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      # Login to dockerhub so that we don't get rate limited
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_READONLY_USERNAME }}
          password: ${{ secrets.DOCKER_READONLY_PASSWORD }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 3600
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: core/chainlink.Dockerfile
          build-args: COMMIT_SHA=${{ github.sha }},ENVIRONMENT=release
          tags: 795953128386.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/chainlink:latest.${{ github.sha }}
          push: true

  smoke:
    needs: build-chainlink
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: /tmp/KUBECONFIG
      CGO_ENABLED: 0
      # APPS_CHAINLINK_IMAGE: 795953128386.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/chainlink
      # APPS_CHAINLINK_VERSION: latest.${{ github.sha }}
      APPS_CHAINLINK_IMAGE: public.ecr.aws/chainlink/chainlink
      APPS_CHAINLINK_VERSION: 0.10.14
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_READONLY_USERNAME }}
          password: ${{ secrets.DOCKER_READONLY_PASSWORD }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 3600
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Prepare KUBECONFIG
        run: echo "${{ secrets.KUBECONFIG }}" > $KUBECONFIG
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Install Ginkgo CLI
        run: go install github.com/onsi/ginkgo/ginkgo
      - name: Download Go Vendor Packages
        run: go mod download
      - name: Run Tests
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          ./tools/ci/smoke_test_chainlink.sh 0
      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: '**/logs/tests-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Artifacts
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: test-logs
          path: ./integration/logs

  performance:
    needs: build-chainlink
    # Only run performance tests on significant PRs
    if: startsWith(github.ref, 'v') || contains(github.ref, 'main') || contains(github.ref, 'develop')
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: /tmp/KUBECONFIG
      CGO_ENABLED: 0
      APPS_CHAINLINK_IMAGE: 795953128386.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/chainlink
      APPS_CHAINLINK_VERSION: latest.${{ github.sha }}
      NETWORK: ethereum_geth_performance
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      # Login to dockerhub so that we don't get rate limited
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_READONLY_USERNAME }}
          password: ${{ secrets.DOCKER_READONLY_PASSWORD }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 3600
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Prepare KUBECONFIG
        run: echo "${{ secrets.KUBECONFIG }}" > $KUBECONFIG
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Install Ginkgo CLI
        run: go install github.com/onsi/ginkgo/ginkgo
      - name: Download Go Vendor Packages
        run: go mod download
      - name: Run Tests
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          ./tools/ci/smoke_test_chainlink.sh 1
      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: '**/logs/tests-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Artifacts
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: test-logs
          path: ./integration/logs
